/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-secondary': '#ffffff',
        surface: '#f8f9ff',
        'on-tertiary-fixed-variant': '#2f2ebe',
        'surface-variant': '#d3e4fe',
        'secondary-container': '#6cf8bb',
        'surface-container-high': '#dce9ff',
        'error-container': '#ffdad6',
        'surface-container-highest': '#d3e4fe',
        'on-error': '#ffffff',
        'inverse-on-surface': '#eaf1ff',
        'on-primary-container': '#7c839b',
        'on-tertiary-fixed': '#07006c',
        'surface-container-low': '#eff4ff',
        'on-primary': '#ffffff',
        'surface-bright': '#f8f9ff',
        'on-secondary-container': '#00714d',
        error: '#ba1a1a',
        primary: '#000000',
        secondary: '#006c49',
        'outline-variant': '#c6c6cd',
        background: '#f8f9ff',
        'surface-dim': '#cbdbf5',
        outline: '#76777d',
        'on-secondary-fixed': '#002113',
        'primary-fixed-dim': '#bec6e0',
        'surface-tint': '#565e74',
        'tertiary-container': '#07006c',
        'secondary-fixed': '#6ffbbe',
        'surface-container': '#e5eeff',
        'on-error-container': '#93000a',
        'primary-fixed': '#dae2fd',
        'on-secondary-fixed-variant': '#005236',
        'on-surface': '#0b1c30',
        'on-surface-variant': '#45464d',
        'on-tertiary-container': '#7073ff',
        tertiary: '#000000',
        'secondary-fixed-dim': '#4edea3',
        'surface-container-lowest': '#ffffff',
        'on-primary-fixed-variant': '#3f465c',
        'tertiary-fixed-dim': '#c0c1ff',
        'tertiary-fixed': '#e1e0ff',
        'inverse-surface': '#213145',
        'on-tertiary': '#ffffff',
        'inverse-primary': '#bec6e0',
        'on-primary-fixed': '#131b2e',
        'on-background': '#0b1c30',
        'primary-container': '#131b2e',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        sm: '12px',
        base: '8px',
        gutter: '24px',
        'container-max': '1280px',
        md: '24px',
        xs: '4px',
        xl: '64px',
        lg: '40px',
      },
      fontFamily: {
        'label-sm': ['Hanken Grotesk'],
        'body-lg': ['Inter'],
        'label-md': ['Hanken Grotesk'],
        'headline-sm': ['Hanken Grotesk'],
        'headline-lg-mobile': ['Hanken Grotesk'],
        'body-md': ['Inter'],
        'body-sm': ['Inter'],
        'headline-lg': ['Hanken Grotesk'],
        'headline-md': ['Hanken Grotesk'],
      },
      fontSize: {
        'label-sm': ['12px', { lineHeight: '14px', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-lg-mobile': ['32px', { lineHeight: '38px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
